from enum import Enum


class League(Enum):
    DEVELOPMENT = 0
    GENERAL = 1
    GEMINI = 2

    def __str__(self):
        return self.name

    def __repr__(self):
        return f"{self.__class__.__name__}({self.value})"


class Competition(Enum):
    OLYMPICS = 1
    PARALYMPICS = 2

    def __str__(self):
        return self.name

    def __repr__(self):
        return f"{self.__class__.__name__}({self.value})"


class OlympicEvents(Enum):
    CYCLING_ROAD_MEN = 1
    TAEKWONDO___58_KG__MEN = 2
    TAEKWONDO___57_KG__WOMEN = 3
    CYCLING_ROAD_WOMEN = 4
    TRIATHLON_MEN = 5
    DIVING___SYNCHRONISED_10M_PLATFORM__MEN = 6
    ARTISTIC_GYMNASTICS__TEAM__MEN = 7
    ARTISTIC_GYMNASTICS__TEAM__WOMEN = 8
    DIVING___SYNCHRONISED_10M_PLATFORM__WOMEN = 9
    TRIATHLON_WOMEN = 10
    SURFING_MEN = 11
    SURFING_WOMEN = 12
    ARTISTIC_GYMNASTICS__ALL_AROUND__MEN = 13
    ARTISTIC_GYMNASTICS__ALL_AROUND__WOMEN = 14
    TABLE_TENNIS__SINGLES__WOMEN = 15
    SWIMMING__800M_FREESTYLE__MEN = 16
    TABLE_TENNIS__SINGLES__MEN = 17
    TRAMPOLINE_GYMNASTICS_WOMEN = 18
    SWIMMING__800M_FREESTYLE__WOMEN = 19
    TRAMPOLINE_GYMNASTICS_MEN = 20
    TENNIS__SINGLES__WOMEN = 21
    TENNIS__SINGLES__MEN = 22
    SWIMMING__4_X_100M_MEDLEY_RELAY__MEN = 23
    SWIMMING__4_X_100M_MEDLEY_RELAY__WOMEN = 24
    SWIMMING__50M_FREESTYLE__MEN = 25
    SWIMMING__50M_FREESTYLE__WOMEN = 26
    ATHLETICS__100M__WOMEN = 27
    ARTISTIC_GYMNASTICS__FLOOR_EXERCISE__MEN = 28
    ATHLETICS__100M__MEN = 29
    ATHLETICS__LONG_JUMP__MEN = 30
    ATHLETICS__TRIPLE_JUMP__WOMEN = 31
    ARTISTIC_GYMNASTICS__FLOOR_EXERCISE__WOMEN = 32
    ATHLETICS__LONG_JUMP__WOMEN = 33
    ATHLETICS__400M_HURDLES__MEN = 34
    ATHLETICS__400M_HURDLES__WOMEN = 35
    SKATEBOARDING__PARK__WOMEN = 36
    SKATEBOARDING__PARK__MEN = 37
    ATHLETICS__TRIPLE_JUMP__MEN = 38
    BEACH_VOLLEYBALL_WOMEN = 39
    FOOTBALL_WOMEN = 40
    BASKETBALL_MEN = 41
    VOLLEYBALL_MEN = 42
    HANDBALL_MEN = 43
    FOOTBALL_MEN = 44
    BEACH_VOLLEYBALL_MEN = 45
    ATHLETICS__MARATHON__WOMEN = 46
    BASKETBALL_WOMEN = 47
    VOLLEYBALL_WOMEN = 48
    HANDBALL_WOMEN = 49
    ATHLETICS__MARATHON__MEN = 50

    def __str__(self):
        return self.name

    def __repr__(self):
        return f"{self.__class__.__name__}({self.value})"


class ParalympicEvents(Enum):
    POWERLIFTING_UP_TO_54_00KG_MEN = 51
    SWIMMING_MIXED_EVENTS__4X50M_FREE_20_POINTS_MIXED = 52
    WHEELCHAIR_FENCING_EPEE_CATEGORY_A_MEN = 53
    ATHLETICS_100M_T47_MEN = 54
    ATHLETICS_CLUB_THROW_F32_WOMEN = 55
    EQUESTRIAN_INDIVIDUAL___GRADE_I_ = 56
    SWIMMING_50M_FLY_S5_WOMEN = 57
    CYCLING_C_1_2_3_KILO__MEN = 58
    ATHLETICS_1500M_T13_WOMEN = 59
    ATHLETICS_5000M_T54_WOMEN = 60
    TABLE_TENNIS_SINGLES___CLASS_9__MEN = 61
    WHEELCHAIR_RUGBY_ = 62
    ATHLETICS_DISCUS_THROW_F64_WOMEN = 63
    ATHLETICS_SHOT_PUT_F20_WOMEN = 64
    EQUESTRIAN_TEAM___OPEN_ = 65
    ROWING_MIXED__DOUBLE_SCULLS_PR2_MIX2X_ = 66
    TRIATHLON_PTWC_WOMEN = 67
    ARCHERY_COMPOUND_WOMEN = 68
    ARCHERY_W1_MEN = 69
    JUDO_OVER_100_00KG_MEN = 70
    SHOOTING_RIFLE_AIR_RIFLE_STANDING_SH1_MEN = 71
    SHOOTING_PISTOL_AIR_PISTOL_SH1_WOMEN = 72
    SWIMMING_100M_BREAST_SB7_MEN = 73
    SWIMMING_50M_FREE_S5_MEN = 74
    WHEELCHAIR_TENNIS_DOUBLES_ = 75
    ATHLETICS_800M_T53_MEN = 76
    SWIMMING_50M_BACK_S1_MEN = 77
    SWIMMING_50M_FREE_S4_WOMEN = 78
    ATHLETICS_4X100M_UNIVERSAL_RELAY_ = 79
    ATHLETICS_HIGH_JUMP_T64_MEN = 80
    ATHLETICS_JAVELIN_THROW_F46_WOMEN = 81
    CANOE_KAYAK_SINGLE_KL1_MEN = 82
    CANOE_VA_A_SINGLE_VL2_WOMEN = 83
    CYCLING_B_ROAD_RACE_WOMEN = 84
    GOALBALL_MEN = 85
    GOALBALL_WOMEN = 86
    SWIMMING_200M_IM_SM10_WOMEN = 87
    TAEKWONDO_K44_OVER_58KG__WOMEN = 88
    ARCHERY_MIXED_TEAM_RECURVE_ = 89
    ATHLETICS_400M_T47_MEN = 90
    ATHLETICS_LONG_JUMP_T20_MEN = 91
    BADMINTON_DOUBLES_SL3_SU5_WOMEN = 92
    BOCCIA_PAIRS___BC3_ = 93
    BOCCIA_PAIRS___BC4_ = 94
    FOOTBALL_5_A_SIDE_MEN = 95
    VOLLEYBALL__SITTING___MEN = 96
    WHEELCHAIR_BASKETBALL__WOMEN = 97
    ATHLETICS_MARATHON_T12_WOMEN = 98
    ATHLETICS_MARATHON_T46_MEN = 99
    BADMINTON_SINGLES_SH6_MEN = 100

    def __str__(self):
        return self.name

    def __repr__(self):
        return f"{self.__class__.__name__}({self.value})"


class NOC(Enum):
    AFGHANISTAN = 1
    ALBANIA = 2
    ALGERIA = 3
    AMERICAN_SAMOA = 4
    ANDORRA = 5
    ANGOLA = 6
    ANTIGUA_AND_BARBUDA = 7
    ARGENTINA = 8
    ARMENIA = 9
    ARUBA = 10
    AUSTRALIA = 11
    AUSTRIA = 12
    AZERBAIJAN = 13
    BAHAMAS = 14
    BAHRAIN = 15
    BANGLADESH = 16
    BARBADOS = 17
    BELARUS = 18
    BELGIUM = 19
    BELIZE = 20
    BENIN = 21
    BERMUDA = 22
    BHUTAN = 23
    BOLIVIA = 24
    BOSNIA_AND_HERZEGOVINA = 25
    BOTSWANA = 26
    BRAZIL = 27
    BRITISH_VIRGIN_ISLANDS = 28
    BRUNEI_DARUSSALAM = 29
    BULGARIA = 30
    BURKINA_FASO = 31
    BURUNDI = 32
    CABO_VERDE = 33
    CAMBODIA = 34
    CAMEROON = 35
    CANADA = 36
    CAYMAN_ISLANDS = 37
    CENTRAL_AFRICAN_REPUBLIC = 38
    CHAD = 39
    CHILE = 40
    CHINESE_TAIPEI = 41
    COLOMBIA = 42
    COMOROS = 43
    CONGO = 44
    CONGO_DR = 45
    COOK_ISLANDS = 46
    COSTA_RICA = 47
    COTE_D_IVOIRE = 48
    CROATIA = 49
    CUBA = 50
    CYPRUS = 51
    CZECH_REPUBLIC = 52
    DEMOCRATIC_PEOPLES_REPUBLIC_OF_KOREA = 53
    DENMARK = 54
    DJIBOUTI = 55
    DOMINICA = 56
    DOMINICAN_REPUBLIC = 57
    ECUADOR = 58
    EGYPT = 59
    EL_SALVADOR = 60
    EQUATORIAL_GUINEA = 61
    ERITREA = 62
    ESTONIA = 63
    ETHIOPIA = 64
    FEDERATED_STATES_OF_MICRONESIA = 65
    FIJI = 66
    FINLAND = 67
    FRANCE = 68
    GABON = 69
    GAMBIA = 70
    GEORGIA = 71
    GERMANY = 72
    GHANA = 73
    GREAT_BRITAIN = 74
    GREECE = 75
    GRENADA = 76
    GUAM = 77
    GUATEMALA = 78
    GUINEA = 79
    GUINEA_BISSAU = 80
    GUYANA = 81
    HAITI = 82
    HONDURAS = 83
    HONG_KONG = 84
    HUNGARY = 85
    ICELAND = 86
    INDIA = 87
    INDONESIA = 88
    IRAQ = 89
    IRELAND = 90
    ISLAMIC_REPUBLIC_OF_IRAN = 91
    ISRAEL = 92
    ITALY = 93
    JAMAICA = 94
    JAPAN = 95
    JORDAN = 96
    KAZAKHSTAN = 97
    KENYA = 98
    KIRIBATI = 99
    KOREA = 100
    KOSOVO = 101
    KUWAIT = 102
    KYRGYZSTAN = 103
    LAO_PEOPLES_DEMOCRATIC_REPUBLIC = 104
    LATVIA = 105
    LEBANON = 106
    LESOTHO = 107
    LIBERIA = 108
    LIBYA = 109
    LIECHTENSTEIN = 110
    LITHUANIA = 111
    LUXEMBOURG = 112
    MADAGASCAR = 113
    MALAWI = 114
    MALAYSIA = 115
    MALDIVES = 116
    MALI = 117
    MALTA = 118
    MARSHALL_ISLANDS = 119
    MAURITANIA = 120
    MAURITIUS = 121
    MEXICO = 122
    MONACO = 123
    MONGOLIA = 124
    MONTENEGRO = 125
    MOROCCO = 126
    MOZAMBIQUE = 127
    MYANMAR = 128
    NAMIBIA = 129
    NAURU = 130
    NEPAL = 131
    NETHERLANDS = 132
    NEW_ZEALAND = 133
    NICARAGUA = 134
    NIGER = 135
    NIGERIA = 136
    NORWAY = 137
    OMAN = 138
    PAKISTAN = 139
    PALAU = 140
    PALESTINE = 141
    PANAMA = 142
    PAPUA_NEW_GUINEA = 143
    PARAGUAY = 144
    PEOPLES_REPUBLIC_OF_CHINA = 145
    PERU = 146
    PHILIPPINES = 147
    POLAND = 148
    PORTUGAL = 149
    PUERTO_RICO = 150
    QATAR = 151
    REPUBLIC_OF_MOLDOVA = 152
    ROMANIA = 153
    RUSSIAN_FEDERATION = 154
    RWANDA = 155
    SAINT_KITTS_AND_NEVIS = 156
    SAINT_LUCIA = 157
    SAINT_VINCENT_AND_THE_GRENADINES = 158
    SAMOA = 159
    SAN_MARINO = 160
    SAO_TOME_AND_PRINCIPE = 161
    SAUDI_ARABIA = 162
    SENEGAL = 163
    SERBIA = 164
    SEYCHELLES = 165
    SIERRA_LEONE = 166
    SINGAPORE = 167
    SLOVAKIA = 168
    SLOVENIA = 169
    SOLOMON_ISLANDS = 170
    SOMALIA = 171
    SOUTH_AFRICA = 172
    SOUTH_SUDAN = 173
    SPAIN = 174
    SRI_LANKA = 175
    SUDAN = 176
    SURINAME = 177
    SWAZILAND = 178
    SWEDEN = 179
    SWITZERLAND = 180
    SYRIAN_ARAB_REPUBLIC = 181
    TAJIKISTAN = 182
    THAILAND = 183
    THE_FORMER_YUGOSLAV_REPUBLIC_OF_MACEDONIA = 184
    TIMOR_LESTE = 185
    TOGO = 186
    TONGA = 187
    TRINIDAD_AND_TOBAGO = 188
    TUNISIA = 189
    TURKEY = 190
    TURKMENISTAN = 191
    TUVALU = 192
    UGANDA = 193
    UKRAINE = 194
    UNITED_ARAB_EMIRATES = 195
    UNITED_REPUBLIC_OF_TANZANIA = 196
    UNITED_STATES_OF_AMERICA = 197
    URUGUAY = 198
    UZBEKISTAN = 199
    VANUATU = 200
    VENEZUELA = 201
    VIET_NAM = 202
    VIRGIN_ISLANDS = 203
    YEMEN = 204
    ZAMBIA = 205
    ZIMBABWE = 206

    def __str__(self):
        return self.name

    def __repr__(self):
        return f"{self.__class__.__name__}({self.value})"
